<?php 

$brokerPairToApiPair = array(
    'AAVEEUR' => 'aaveeur',
    'ADAEUR' => 'adaeur',
    'ALGOEUR' => 'algoeur',
    'ATOMEUR' => 'atomeur',
    'BALEUR' => 'baleur',
    'BATEUR' => 'bateur',
    'BCHEUR' => 'bcheur',
    'COMPEUR' => 'compeur',
    'CRVEUR' => 'crveur',
    'DAIEUR' => 'daieur',
    'DASHEUR' => 'dasheur',
    'DOTEUR' => 'doteur',
    'EOSEUR' => 'eoseur',
    'FILEUR' => 'fileur',
    'FLOWEUR' => 'floweur',
    'GNOEUR' => 'gnoeur',
    'GRTEUR' => 'grteur',
    'KAVAEUR' => 'kavaeur',
    'KEEPEUR' => 'keepeur',
    'KNCEUR' => 'knceur',
    'KSMEUR' => 'ksmeur',
    'ICXEUR' => 'icxeur',
    'LINKEUR' => 'linkeur',
    'LSKEUR' => 'lskeur',
    'MANAEUR' => 'manaeur',
    'NANOEUR' => 'nanoeur',
    'OMGEUR' => 'omgeur',
    'OXTEUR' => 'oxteur',
    'QTUMEUR' => 'qtumeur',
    'REPV2EUR' => 'repv2eur',
    'SCEUR' => 'sceur',
    'STORJEUR' => 'storjeur',
    'TRXEUR' => 'trxeur',
    'UNIEUR' => 'unieur',
    'WAVESEUR' => 'waveseur',
    'XDGEUR' => 'dogeeur',
    'XETHZEUR' => 'etheur',
    'XETCZEUR' => 'etceur',
    'XLTCZEUR' => 'ltceur',
    'XREPZEUR' =>  'repeur',
    'XTZEUR' => 'xtzeur',
    'XXMRZEUR' => 'xmreur',
    'XXBTZEUR' => 'btceur',
    'XXRPZEUR' => 'xrpeur',
    'XXLMZEUR' => 'xlmeur',
    'XZECZEUR' => 'zeceur'
);

?>